### ISSUE TITLE
failed to compile in my React app

### ISSUE THREAD

**Issue by JasonPWhite** [aralroca/default-composer#15]
"default-composer": "^0.4.0"

NODE v16.13.0    NPM 16.13.0 (Currently using 64-bit executable)

Failed to compile  on npm start

Failed to compile.

Module parse failed: Unexpected token (30:33)
|         },
|         p = o(b),
>         s = e.isDefaultableValue?.(_objectSpread({}, b, {
|           defaultableValue: p
|         })) ?? p;

I expected the app to start

Sorry I cannot submit pull request due to NDA

**Comment by aralroca** [comment]
@JasonPWhite Can you try if in `"default-composer": "0.3.0"` is working in your project? Because in 3.1 we introduced a change in the default export and maybe is for this...! Thanks for the feedback

**Comment by JasonPWhite** [comment]
Thanks for your email Aral,

I will try this and let you know.

Kind regards,

Jason

**Comment by aralroca** [comment]
@JasonPWhite waiting your feedback, if is not working would be great to share a reproducible example. Thanks

**Comment by aralroca** [comment]
Already solved in https://github.com/aralroca/default-composer/releases/tag/0.5.1

**Comment by JasonPWhite** [comment]
Hi, apologies, I have been away from my project that I intended to use
Default Composer with, but I will be back to it some time soon.  I will let
you know how it goes.  Thanks for the response.

Kind regards,

Jason

**Comment by aralroca** [comment]
@JasonPWhite I guess was related with this another issue https://github.com/aralroca/default-composer/issues/20
