### ISSUE TITLE
Module not found: Default condition should be last one

### ISSUE THREAD

**Issue by robs0n** [aralroca/default-composer#20]
First of all: thank you for this nice tiny lib! 👍 

**What version of this package are you using?**
`0.5.0`

**What operating system, Node.js, and npm version?**
node: `v18.15.0`, yarn: `4.0.0-rc.45`

**What happened?**
I would like to use `default-composer` in a NextJS-Project and got the following error on importing:
```
next:dev: Module not found: Default condition should be last one
...
next:dev: > 4 | import { defaultComposer } from "default-composer";
```
Accoording to [Node-Specification about conditional exports](https://nodejs.org/api/packages.html#conditional-exports):
> "default" - the generic fallback that always matches. Can be a CommonJS or ES module file. This condition should always come last. 

I tried to change it locally from:
```json
  "exports": {
    "require": "./dist/index.js",
    "default": "./dist/index.modern.mjs",
    "types": "./dist/index.d.ts"
  }
```
to
```json
"exports": {
    "require": "./dist/index.js",
    "types": "./dist/index.d.ts",
    "default": "./dist/index.modern.mjs"
  }
```

and the error is gone.

Could you please have a look.

**Comment by aralroca** [comment]
Thank you @robs0n to report 🙏😊 I already fixed in 0.5.1 https://github.com/aralroca/default-composer/commit/a2920adaf81405982e1deaecd42506f68e05caeb
