### ISSUE TITLE
Default-composer lost type with mathjs

### ISSUE THREAD

**Issue by dellorogiulio** [aralroca/default-composer#21]
**What version of this package are you using?**
0.5.1

**What operating system, Node.js, and npm version?**
Windows, node 18.15.0, npm 9.6.3

**What happened?**
Passing through default-composer make object to lose methods and other attributes
See code below:
```
import { unit, isUnit } from "mathjs";
import { defaultComposer } from "default-composer";

const def = {
  a: unit(0, "mm"),
  b: unit(0, "mm"),
  c: unit(0, "mm"),
};

const dim = {
  a: unit(1, "mm"),
  b: unit(2, "mm"),
  c: unit(3, "mm"),
};

console.log(isUnit(dim.a)); // returns true since a is of type mathjs.Unit
const full = defaultComposer(def, dim);
console.log(isUnit(full.a)); // returns false since a is missing of some attributes of mathjs.Unit
```

I think that during the 'compose' function, you not check for methods (aka functions) on object and (maybe) other stuffs. This make a complex object to lose some attributes.

**Comment by aralroca** [comment]
It was closed automatically on merge the PR. In reality the PR is fixing the instance of any class. Probably is also fixing mathjs or maybe not, can you verify it @dellorogiulio ? If it's already failing I'm going to investigate what is happening with this library. Thanks a lot!

**Comment by dellorogiulio** [comment]
Hi @aralroca, everything seems ok, at least with some minimal examples on different types of mathjs.
Thanks!
